exclude = { glob = "*.lock" }

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    { id = "trailing-whitespace" },
    { id = "end-of-file-fixer" },
    { id = "check-toml" },
    { id = "check-yaml" },
]

[[repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "v4.13.9"
hooks = [
    { id = "commitizen", stages = ["commit-msg"] },
]

[[repos]]
repo = "https://github.com/kamadorueda/alejandra"
rev = "4.0.0"
hooks = [
    { id = "alejandra" },
]

[[repos]]
repo = "https://github.com/typstyle-rs/pre-commit-typstyle"
rev = "v0.14.4"
hooks = [
    { id = "typstyle", args = ["--line-width", "120", "--indent-width", "2"] },
]
